import type { Challenge } from "@/types/gamification";

export const MISSION_STATS = {
  activeFinders: 247,
  talentsTipped: 68,
  totalXpEarned: 24500,
  completedMissions: 156,
};

export const CHALLENGES: Challenge[] = [
  {
    id: "first-recommendation",
    icon: "👥",
    title: "Eerste introductie",
    description: "Stuur je eerste introductie en zet de eerste stap.",
    goal: "1 introductie verstuurd",
    reward: "Eerste erkenning",
    current: 0,
    target: 1,
    status: "active",
    trackType: "tips",
    xpReward: 100,
  },
  {
    id: "first-interview",
    icon: "📅",
    title: "Eerste gesprek",
    description: "Zodra een kandidaat in gesprek raakt, groeit jouw reputatie mee.",
    goal: "1 gesprek gepland",
    reward: "Meer vertrouwen",
    current: 0,
    target: 1,
    status: "active",
    trackType: "intake",
    xpReward: 250,
  },
  {
    id: "first-hire",
    icon: "🎯",
    title: "Eerste plaatsing",
    description: "Een eerste succesvolle plaatsing laat zien dat jouw netwerk impact maakt.",
    goal: "1 kandidaat aangenomen",
    reward: "Sterkere reputatie",
    current: 0,
    target: 1,
    status: "active",
    trackType: "match",
    xpReward: 500,
  },
  {
    id: "first-reward",
    icon: "🏆",
    title: "Eerste beloning",
    description: "Wanneer een plaatsing standhoudt, volgt de hoogste beloning.",
    goal: "1 beloning uitbetaald",
    reward: "Beloning ontvangen",
    current: 0,
    target: 1,
    status: "active",
    trackType: "keeper",
    xpReward: 1000,
  },
];
