import type { Activity, Candidate, Scout } from "@/types";

export const CURRENT_USER = "Joshua Souisay";

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: "c1",
    name: "Kevin de Vries",
    emailOrPhone: "kevin@email.nl",
    linkedin: "linkedin.com/in/kevindv",
    role: "Productie",
    sector: "Productie",
    referredBy: CURRENT_USER,
    status: "nieuw",
    xpAwarded: 35,
    confidenceScore: 85,
    cashStatus: "plaatsing_in_behandeling",
    duplicateStatus: "uniek",
    referralApproval: "goedgekeurd",
    reasons: ["Staat open voor een nieuwe uitdaging"],
    relationship: "gewerkt",
    recommendation: "Kevin is een ervaren operator die openstaat voor een nieuwe stap.",
    createdAt: "2026-06-09T10:30:00",
  },
  {
    id: "c2",
    name: "Emma Jansen",
    emailOrPhone: "06-12345678",
    role: "Kantoor",
    sector: "Kantoor",
    referredBy: CURRENT_USER,
    status: "intake_gepland",
    xpAwarded: 85,
    confidenceScore: 72,
    cashStatus: "intake_in_behandeling",
    duplicateStatus: "uniek",
    referralApproval: "goedgekeurd",
    reasons: ["Zoekt groeimogelijkheden"],
    relationship: "persoonlijk",
    createdAt: "2026-06-08T14:00:00",
  },
  {
    id: "c3",
    name: "Mike van Dijk",
    emailOrPhone: "mike@email.nl",
    linkedin: "linkedin.com/in/mikevd",
    role: "Techniek",
    sector: "Techniek",
    referredBy: CURRENT_USER,
    status: "geplaatst",
    xpAwarded: 685,
    confidenceScore: 90,
    cashStatus: "plaatsing_goedgekeurd",
    duplicateStatus: "uniek",
    referralApproval: "goedgekeurd",
    reasons: ["Heeft sterke technische kennis"],
    relationship: "gewerkt",
    createdAt: "2026-06-01T09:00:00",
  },
  {
    id: "c4",
    name: "Lisa Vermeer",
    emailOrPhone: "lisa@email.nl",
    role: "Kantoor",
    sector: "Kantoor",
    referredBy: "Kevin de Vries",
    status: "voorgesteld",
    xpAwarded: 160,
    confidenceScore: 65,
    cashStatus: "geen_cash",
    duplicateStatus: "uniek",
    referralApproval: "goedgekeurd",
    reasons: ["Past goed bij een openstaande vacature"],
    relationship: "netwerk",
    createdAt: "2026-06-07T11:00:00",
  },
  {
    id: "c5",
    name: "Tom Bakker",
    emailOrPhone: "tom@email.nl",
    role: "Sales",
    sector: "Sales",
    referredBy: "Emma Bakker",
    status: "nieuw",
    xpAwarded: 10,
    confidenceScore: 35,
    cashStatus: "geen_cash",
    duplicateStatus: "onder_review",
    referralApproval: "pending",
    reasons: [],
    relationship: "online",
    createdAt: "2026-06-09T08:00:00",
  },
  {
    id: "c6",
    name: "Sara de Jong",
    emailOrPhone: "06-98765432",
    role: "Management",
    sector: "Management",
    referredBy: CURRENT_USER,
    status: "proeftijd_gehaald",
    xpAwarded: 1685,
    confidenceScore: 88,
    cashStatus: "retentie_goedgekeurd",
    duplicateStatus: "uniek",
    referralApproval: "goedgekeurd",
    reasons: ["Heeft leidinggevende ervaring"],
    relationship: "gewerkt",
    createdAt: "2026-05-15T10:00:00",
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "a1",
    text: "Kevin de Vries getipt",
    xp: 35,
    timestamp: "2026-06-09T10:30:00",
  },
  {
    id: "a2",
    text: "Emma Jansen intake gepland",
    xp: 50,
    timestamp: "2026-06-08T14:00:00",
  },
  {
    id: "a3",
    text: "Mike van Dijk succesvolle match",
    xp: 500,
    timestamp: "2026-06-01T09:00:00",
  },
];

export const INITIAL_LEADERBOARD: Scout[] = [
  { rank: 1, name: "Lennart Lakeman", xp: 7250, placements: 8, keepers: 5, reward: 2000 },
  { rank: 2, name: "Emma Bakker", xp: 6180, placements: 6, keepers: 4, reward: 1500 },
  { rank: 3, name: "Peter Jansen", xp: 5430, placements: 5, keepers: 3, reward: 1250 },
  { rank: 4, name: "Mike de Groot", xp: 4980, placements: 4, keepers: 2, reward: 1000 },
  { rank: 5, name: "Sophie van der Meer", xp: 4750, placements: 4, keepers: 2, reward: 1000 },
  { rank: 6, name: "Kevin de Vries", xp: 4310, placements: 3, keepers: 2, reward: 750 },
  {
    rank: 7,
    name: CURRENT_USER,
    xp: 4250,
    placements: 4,
    keepers: 2,
    reward: 1250,
    isCurrentUser: true,
  },
];

export const DASHBOARD_STATS = {
  candidatesReferred: 18,
  successfulPlacements: 4,
  totalReward: 1250,
  regionRank: 7,
  region: "Finderz League",
};

export const LEADERBOARD_MONTHLY: Scout[] = [
  { rank: 1, name: "Emma Bakker", xp: 2180, placements: 2, reward: 500 },
  { rank: 2, name: "Lennart Lakeman", xp: 1950, placements: 2, reward: 500 },
  { rank: 3, name: "Peter Jansen", xp: 1720, placements: 1, reward: 250 },
  { rank: 4, name: "Mike de Groot", xp: 1480, placements: 1, reward: 250 },
  { rank: 5, name: "Sophie van der Meer", xp: 1320, placements: 1, reward: 250 },
  { rank: 6, name: "Kevin de Vries", xp: 980, placements: 1, reward: 250 },
  {
    rank: 7,
    name: CURRENT_USER,
    xp: 860,
    placements: 1,
    reward: 250,
    isCurrentUser: true,
  },
];

export const LEADERBOARD_WK_LEAGUE: Scout[] = [
  { rank: 1, name: "Lennart Lakeman", xp: 1250, placements: 1, reward: 500 },
  { rank: 2, name: "Emma Bakker", xp: 980, placements: 1, reward: 500 },
  { rank: 3, name: "Peter Jansen", xp: 720, placements: 0, reward: 0 },
  { rank: 4, name: "Mike de Groot", xp: 650, placements: 0, reward: 0 },
  { rank: 5, name: "Sophie van der Meer", xp: 520, placements: 0, reward: 0 },
  { rank: 6, name: "Kevin de Vries", xp: 410, placements: 0, reward: 0 },
  {
    rank: 7,
    name: CURRENT_USER,
    xp: 380,
    placements: 0,
    reward: 0,
    isCurrentUser: true,
  },
];
