import type { ScoutBadge } from "@/types/gamification";

export const SCOUT_BADGES: ScoutBadge[] = [
  {
    id: "first-candidate",
    icon: "🔥",
    name: "Eerste Kandidaat",
    description: "Draag je eerste kandidaat aan",
    howToEarn: "Draag je allereerste kandidaat aan via het platform.",
    meaning: "Je bent officieel actief als Scout binnen Finderz Keeperz.",
    earned: true,
    earnedAt: "2026-05-01",
  },
  {
    id: "first-placement",
    icon: "🏆",
    name: "Eerste Plaatsing",
    description: "Realiseer je eerste succesvolle plaatsing",
    howToEarn: "Realiseer je eerste succesvolle plaatsing als Scout.",
    meaning: "Je referrals leveren echte resultaat op voor kandidaat en klant.",
    earned: true,
    earnedAt: "2026-05-20",
  },
  {
    id: "productie-scout",
    icon: "🏭",
    name: "Productie Scout",
    description: "Specialisatie in productie",
    howToEarn: "Draag meerdere kwalitatieve kandidaten binnen productie aan.",
    meaning: "Je hebt meerdere kandidaten binnen productie aangedragen.",
    earned: true,
    earnedAt: "2026-05-28",
  },
  {
    id: "techniek-scout",
    icon: "⚙️",
    name: "Techniek Scout",
    description: "Specialisatie in techniek",
    howToEarn: "Draag meerdere kandidaten binnen techniek aan.",
    meaning: "Je netwerk en expertise liggen sterk in technische functies.",
    earned: false,
  },
  {
    id: "bouw-scout",
    icon: "🏗",
    name: "Bouw Scout",
    description: "Specialisatie in bouw",
    howToEarn: "Draag meerdere kandidaten binnen bouw aan.",
    meaning: "Je signaleert talent in de bouwsector.",
    earned: false,
  },
  {
    id: "logistiek-scout",
    icon: "🚛",
    name: "Logistiek Scout",
    description: "Specialisatie in logistiek",
    howToEarn: "Draag meerdere kandidaten binnen logistiek aan.",
    meaning: "Je bent een betrouwbare Scout in logistiek en supply chain.",
    earned: false,
  },
  {
    id: "golden-boot",
    icon: "⚽",
    name: "Golden Boot Scout",
    description: "WK-plaatsing",
    howToEarn: "Realiseer een plaatsing tijdens het WK Scout League.",
    meaning: "Je presteerde op het hoogste niveau tijdens het WK-seizoen.",
    earned: false,
  },
  {
    id: "elite-keeper",
    icon: "🧤",
    name: "Elite Keeper",
    description: "5 WK-referrals",
    howToEarn: "Draag 5 kandidaten aan tijdens het WK.",
    meaning: "Consistente activiteit en betrokkenheid tijdens het WK.",
    earned: false,
  },
  {
    id: "elite-scout",
    icon: "💎",
    name: "Elite Scout",
    description: "Elite Scout level",
    howToEarn: "Bereik het Elite Scout level (4.000+ XP).",
    meaning: "Je behoort tot de top Scouts qua activiteit en progressie.",
    earned: true,
    earnedAt: "2026-06-01",
  },
  {
    id: "fk-legend",
    icon: "👑",
    name: "FK Legend",
    description: "Legendarisch level",
    howToEarn: "Bereik 10.000 XP als Scout.",
    meaning: "Hall of Fame status binnen Finderz Keeperz.",
    earned: false,
  },
];
