import type { ScoutBadge } from "@/types/gamification";

export const SCOUT_BADGES: ScoutBadge[] = [
  {
    id: "first-talent",
    icon: "🔥",
    name: "First Talent",
    description: "Tip je eerste talent",
    howToEarn: "Tip je allereerste talent via het Finderz Network.",
    meaning: "Je bent officieel actief als Finder binnen Finderz Keeperz.",
    earned: true,
    earnedAt: "2026-05-01",
  },
  {
    id: "keeper-maker",
    icon: "🧤",
    name: "Keeper Maker",
    description: "Succesvolle match gerealiseerd",
    howToEarn: "Help een getipt talent aan een succesvolle match.",
    meaning: "Je hebt een talent geholpen aan een succesvolle match.",
    earned: true,
    earnedAt: "2026-05-20",
  },
  {
    id: "production-finder",
    icon: "🏭",
    name: "Production Finder",
    description: "Specialisatie in productie",
    howToEarn: "Tip meerdere sterke talenten binnen productie.",
    meaning: "Je netwerk en expertise liggen sterk in productie.",
    earned: true,
    earnedAt: "2026-05-28",
  },
  {
    id: "technical-finder",
    icon: "⚙️",
    name: "Technical Finder",
    description: "Specialisatie in techniek",
    howToEarn: "Tip meerdere talenten binnen techniek.",
    meaning: "Je herkent betrouwbaar technisch talent in je netwerk.",
    earned: false,
  },
  {
    id: "construction-finder",
    icon: "🏗",
    name: "Construction Finder",
    description: "Specialisatie in bouw",
    howToEarn: "Tip meerdere talenten binnen bouw.",
    meaning: "Je signaleert talent in de bouwsector.",
    earned: false,
  },
  {
    id: "top-tipper",
    icon: "🎯",
    name: "Top Tipper",
    description: "Meerdere sterke talenttips",
    howToEarn: "Doe meerdere talenttips met een hoge Talent Confidence Score.",
    meaning: "Je hebt meerdere sterke talenttips gedaan.",
    earned: false,
  },
  {
    id: "golden-boot",
    icon: "⚽",
    name: "Golden Boot Mission",
    description: "WK-match gerealiseerd",
    howToEarn: "Realiseer een succesvolle match tijdens de WK Finderz Mission.",
    meaning: "Je presteerde op het hoogste niveau tijdens het WK-seizoen.",
    earned: false,
  },
  {
    id: "elite-finder",
    icon: "💎",
    name: "Elite Finder",
    description: "Elite Finder level",
    howToEarn: "Bereik het Elite Finder level (1.500+ XP).",
    meaning: "Je behoort tot de top Finders qua activiteit en progressie.",
    earned: true,
    earnedAt: "2026-06-01",
  },
  {
    id: "finderz-legend",
    icon: "👑",
    name: "Finderz Legend",
    description: "Legendarisch level",
    howToEarn: "Bereik 10.000 XP als Finder.",
    meaning: "Hall of Fame status binnen Finderz Keeperz.",
    earned: false,
  },
];
