import type { Challenge } from "@/types/gamification";

export const MISSION_STATS = {
  activeFinders: 247,
  talentsTipped: 68,
  totalXpEarned: 24500,
  completedMissions: 156,
};

export const CHALLENGES: Challenge[] = [
  {
    id: "tip-3-talents",
    icon: "👥",
    title: "Talent Tipper",
    description: "Draag 3 talenten aan via het Finderz Network.",
    goal: "3 talenten getipt",
    reward: "+100 XP",
    current: 0,
    target: 3,
    status: "active",
    trackType: "tips",
    xpReward: 100,
  },
  {
    id: "intake-mission",
    icon: "📅",
    title: "Intake Mission",
    description: "Laat een talent op intake komen.",
    goal: "1 intake gepland",
    reward: "+250 XP",
    current: 0,
    target: 1,
    status: "active",
    trackType: "intake",
    xpReward: 250,
  },
  {
    id: "match-mission",
    icon: "🎯",
    title: "Match Mission",
    description: "Behaal een succesvolle match.",
    goal: "1 succesvolle match",
    reward: "+500 XP",
    current: 0,
    target: 1,
    status: "active",
    trackType: "match",
    xpReward: 500,
  },
  {
    id: "expert-vacancy-mission",
    icon: "🔴",
    title: "Expert Mission",
    description:
      "Tip talent voor een Expert vacature en behaal een succesvolle match.",
    goal: "1 match op Expert vacature",
    reward: "+750 XP",
    current: 0,
    target: 1,
    status: "active",
    trackType: "manual",
    xpReward: 750,
  },
  {
    id: "keeper-mission",
    icon: "🏆",
    title: "Keeper Mission",
    description: "Behaal Keeper Status met een talent.",
    goal: "1 Keeper Status",
    reward: "+1000 XP",
    current: 0,
    target: 1,
    status: "active",
    trackType: "keeper",
    xpReward: 1000,
  },
  {
    id: "team-oranje",
    icon: "🏟",
    title: "Community Mission",
    description:
      "Community doel: alle Finders samen 100 talenten getipt.",
    goal: "100 talenten getipt (community)",
    reward: "Iedere actieve Finder ontvangt +500 XP",
    current: 42,
    target: 100,
    status: "active",
    isCommunity: true,
    trackType: "manual",
  },
];
