services:
  - type: web
    name: referr-platform
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_DEMO_MODE
        value: "true"
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
