-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "companyName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "jobTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "companyCity" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "companyKvK" TEXT NOT NULL DEFAULT '';
